### ISSUE TITLE
How to search the drug and their target in data of drug bank after reading it into R by "yduan004/drugbankR" 

### ISSUE THREAD

**Issue by lone-could** [girke-lab/drugbankR#2]
Dear author of "drugbankR":
 I  have used drugbankR to read the data of drugbank into R.  I wonder that how can I get  the drug approved by FDA for treating lung cancer and their targets in  data.frame named "all"as shown in your Rmd ?
In the website of Drugbank, I can get that drug for  treating lung cancer  by inputting "lung cancer" in  search box. But it's time-consuming to collect their targets one by one. 
In this case I wonder can I get the drug for specified diseases and their targets in R via a convient way.
I look forward to your answer, thank you!

**Comment by yduan004** [comment]
Since you already have the `all` data.frame, I think one possible solution could be searching `lung cancer` in `indication` and `mechanism-of-action` columns of `all` table. In this way, you could get a list of drugs and their drugbank ids. Then run `queryDB` to get their targets and whether FDA approved. 

Here is the code I wrote:
```r
library(drugbankR)
all <- queryDB(type = "getAll", db_path="drugbank_5.1.3.db") 
idx = unique(c(grep("lung cancer", all$`mechanism-of-action`), grep("lung cancer", all$indication)))
head(all[idx, c("drugbank-id","name","indication", "fda-label")])
drugs = all$`drugbank-id`[idx]
targets = queryDB(ids=drugs, type="getTargets", db_path = "drugbank_5.1.3.db")
fda = queryDB(ids=drugs, type="whichFDA", db_path = "drugbank_5.1.3.db")
``` 
I hope it is helpful for your question. If you have any problems, please feel free to let me know. I have subscribed this thread, so I could reply you in time. Thanks for using this package :)
