### ISSUE TITLE
Delimiter between multiple information in a field

### ISSUE THREAD

**Issue by bazoogis** [girke-lab/drugbankR#3]
Dear yduan004,
I have used drugbankR to read the Drugbank database into a dataframe. However, I've noticed that for certain columns (such as ATC-codes), when there are multiple information for a field for a drug, they get concatenated together. For example, for DB00001 (Lepirudin), the respective Drugbank entry reads for the column atc-codes is as follows:

B01AE — Direct thrombin inhibitors
B01A — ANTITHROMBOTIC AGENTS
B01 — ANTITHROMBOTIC AGENTS
B — BLOOD AND BLOOD FORMING ORGANS

In the R dataframe this field is displayed as: "Direct thrombin inhibitorsANTITHROMBOTIC AGENTSANTITHROMBOTIC AGENTSBLOOD AND BLOOD FORMING ORGANS".

This is the case for all columns containing multiple information in a single field (categories, products, mixtures, etc).
I am wondering if it would be possible to include a delimiter (perhaps a semicolon) between each different string so it would be easier to parse. (So the results inside the field would be "Direct thrombin inhibitors; ANTITHROMBOTIC AGENTS; ANTITHROMBOTIC AGENTS; BLOOD AND BLOOD FORMING ORGANS"). Thank you in advance.

Best regards,
Bill Z.

**Comment by yduan004** [comment]
Dear Bill,

I am sorry for replying you late.. Unfortunately, I also noticed this problem but currently it is not easy to be fixed by myself since the data frame is parsed by using the `XML` package, the specific function/code line is `tmp <- xmlToDataFrame(rootnode[i], stringsAsFactors = FALSE, collectNames = FALSE)`. It automatically concatenates multiple items in a field without any delimiter and does not have a parameter to allow setting delimiters.. 

I am sorry for the inconvenience. If you really need it works, you could try to parse the DrugBank XML file to data frame by yourself from another way or trying other XML file processing packages. 

Best regards,
Yuzhu Duan

**Comment by bazoogis** [comment]
Dear Yuzhu,

Thank you for your reply. It is unfortunate that there is no easy solution to this. I will try using a different package for that same end. 

Best regards,
Bill Z.
